# Generated by Django 4.0.3 on 2022-05-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="approved_status",
            field=models.TextField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approve", "Approve"),
                    ("Reject", "Reject"),
                ],
                default="Pending",
            ),
        ),
    ]
