# Generated by Django 4.0.3 on 2022-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0002_alter_project_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved_status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
