# Generated by Django 3.2.12 on 2022-04-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='posted_on_tg',
            field=models.BooleanField(default=False),
        ),
    ]
