# Generated by Django 4.0.4 on 2022-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0003_project_posted_on_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
