# Generated by Django 4.0.4 on 2022-05-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0005_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='approved_status',
        ),
    ]
