name: Linter
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install flake8
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8 csec_project_catalog
  
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort --check --diff csec_project_catalog

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable
  
  django-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: "csec_project_catalog"
          POSTGRES_USER: "csec_project_catalog"
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Testing Django
        run: |
          cd csec_project_catalog
          python manage.py test
        
        env:
          ENGINE: "django.db.backends.postgresql"
          NAME: "csec_project_catalog"
          USER: "csec_project_catalog"
          PASSWORD: ${{ secrets.DB_PASSWORD }}
          HOST: 5432
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
